---
title: "Additional Material"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Additional Material}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This page contains links to additional material for Livestock Breeding and Genomics (FS 2021).

# Slides

```{r slide-table, echo=FALSE, message=FALSE, warning=FALSE}
root_url <- "https://charlotte-ngs.github.io/lbgfs2021" 
sl_url <- paste0(root_url, "/sl/")
misc_url <- paste0(root_url, "/misc/")
tbl_sl <- tibble::tibble(Nr = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
                         Date = c("2021-09-24",
                                  "2021-10-01",
                                  "2021-10-01",
                                  "2021-10-08",
                                  "2021-10-15",
                                  "2021-10-29",
                                  "2021-11-05",
                                  "2021-11-12",
                                  "2021-11-12",
                                  "2021-11-19"),
                         Topic = c(
                           paste0("[Introduction to Livestock Breeding and Genomics](", sl_url, "lbgfs2021_slides_l01_intro_lbg.pdf)", collapse = ""),
                           paste0("[Basics of Quantitative Genetics](", sl_url, "lbgfs2021_slides_l02_basics_qg.pdf)", collapse = ""),
                           paste0("[Introduction to RMarkdown](", misc_url, "20211001_introduction_rmarkdown.pdf)", collapse = ""),
                           paste0("[SESAM Project](", sl_url, "20211008_sesam_project.pdf)", collapse = ""),
                           paste0("[Genetic Evaluation](", sl_url, "lbgfs2021_slides_l03_gen-eval.pdf)", collapse = ""),
                           paste0("[BLUP](", sl_url, "lbgfs2021_slides_l04_blup.pdf)", collapse = ""),
                           paste0("[Genetic Covariances](", sl_url, "lbgfs2021_slides_l05_gencov.pdf)", collapse = ""),
                           paste0("[Numerator Relationship Matrix](", sl_url, "lbgfs2021_l06_slides_numrelmat.pdf)", collapse = ""),
                           paste0("[Inverse Numerator Relationship Matrix](", sl_url, "lbgfs2021_l06_slides_invnumrelmat.pdf)", collapse = ""),
                           paste0("[Variance and Inbreeding](", sl_url, "lbgfs2021_l07_slides_var_inb.pdf)", collapse = "")
                         ))
knitr::kable(tbl_sl)
```


# Videos

```{r video-table, echo=FALSE, message=FALSE, warning=FALSE}
tbl_video <- tibble::tibble(Nr = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13),
                            Date = c("2021-09-24",
                                     "2021-09-24",
                                     "2021-10-01",
                                     "2021-10-08",
                                     "2021-10-08",
                                     "2021-10-08",
                                     "2021-10-15",
                                     "2021-10-22",
                                     "2021-10-29",
                                     "2021-11-05",
                                     "2021-11-12",
                                     "2021-11-12",
                                     "2021-11-19"),
                            Topic = c(
                              "[Introduction to Livestock Breeding and Genomics, Part 1](https://youtu.be/9R2rW-lutfs)", 
                              "[Introduction to Livestock Breeding and Genomics, Part 2](https://youtu.be/7Hn6hlpXiDQ)",
                              "[Introduction to RMarkdown and Basics of Quantitative Genetics (Part 1)](https://youtu.be/rq4Z__gtUcQ)",
                              "[SESAM Project](https://youtu.be/EASemfg4moc)",
                              "[Introduction to Quantitative Genetics (Part 2)](https://youtu.be/X-hjCf7CX7w)",
                              "[Introduction to Quantitative Genetics (Part 3)](https://youtu.be/Asw7PMOwgJk)",
                              "[Genetic Evaluation](https://youtu.be/X7Qq3E7dP8g)",
                              "[Prediction of Breeding Values](https://youtu.be/K3nYZIv_CB0)",
                              "[Selection Index, BLUP and Mixed Linear Effect Models](https://youtu.be/TaKxOeVKLqs)",
                              "[BLUP Sire Model](https://youtu.be/AOvMFpBo_PE)",
                              "[BLUP Animal Model](https://youtu.be/csjJKd14bF4)",
                              "[Numerator Relationship Matrix and its Inverse](https://youtu.be/T9q88r0DUSA)",
                              "[Inverse Numerator Relationship Matrix](https://youtu.be/NQwmXiFK8do)"
                            ))
knitr::kable(tbl_video)
```


# Overhead Projector Pictures

```{r ohp-table, echo=FALSE, message=FALSE, warning=FALSE}
ohp_url <- paste0(root_url, "/ohp/")
tbl_ohp <- tibble::tibble(Nr = c(1, 2, 3, 4, 5, 6, 7, 8, 9),
                          Date = c("2021-09-24",
                                   "2021-10-01",
                                   "2021-10-08",
                                   "2021-10-15",
                                   "2021-10-22",
                                   "2021-10-29",
                                   "2021-11-05",
                                   "2021-11-12",
                                   "2021-11-19"),
                          Topic = c(
                            paste0("[Introduction to Livestock Breeding and Genomics](", ohp_url, "20210924_ohp_pictures.pdf)", collapse = ""),
                            paste0("[Introduction to RMarkdown and Basics of Quantitative Genetics (Part 1)](", ohp_url, "20211001_ohp_pictures.pdf)", collapse = ""),
                            paste0("[SESAM Project and Quantitative Genetics (Part2)](", ohp_url, "20211008_ohp_pictures.pdf)", collapse = ""),
                            paste0("[Genetic Evaluation](", ohp_url, "20211015_ohp_pictures.pdf)", collapse = ""),
                            paste0("[Prediction of Breeding Values](", ohp_url, "20211022_ohp_pictures.pdf)", collapse = ""),
                            paste0("[Selection Index and BLUP](", ohp_url, "20211029_ohp_pictures.pdf)", collapse = ""),
                            paste0("[Sire Model](", ohp_url, "20211105_ohp_pictures.pdf)", collapse = ""),
                            paste0("[Animal Model](", ohp_url, "20211112_ohp_pictures.pdf)", collapse = ""),
                            paste0("[Inverse Numerator Relationship Matrix](", ohp_url, "20211119_ohp_pictures.pdf)", collapse = "")
                          ))
knitr::kable(tbl_ohp)
```


# Notebooks

```{r nb-table, echo=FALSE, message=FALSE, warning=FALSE}
nb_url <- paste0(root_url, "/nb/")
tbl_nb <- tibble::tibble(Nr = c(1),
                         Date = c("2021-10-15"),
                         Topic = c(
                           paste0("[Central Limit Theorem](", nb_url, "20211015_explain_clt.nb.html)", collapse = "")
                         ))
knitr::kable(tbl_nb)
```


# Data

```{r data-table, echo=FALSE, message=FALSE, warning=FALSE}
data_url <- paste0(root_url, "/data/")
tbl_data <- tibble::tibble(Nr = c(1),
                           Date = "2021-10-29",
                           Topic = c(
                             paste0("[Beef Data for BLUP](", data_url, "beef_data_blup.csv)", collapse = "")
                           ))
knitr::kable(tbl_data)
```


```{r latest-change, echo=FALSE, results='asis'}
cat(rmdhelp::get_latest_change())
```

