---
title: "Course Notes"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Course Notes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This page contains a list of chapters of the course notes for Livestock Breeding and Genomics  (FS 2021).

# Chapters

```{r chapter-table, echo=FALSE, message=FALSE, warning=FALSE}
s_cn_url <- "https://charlotte-ngs.github.io/lbgfs2021/cn/"
tbl_chpt <- tibble::tibble(Nr      = c(1, 2, 3, 4),
                           Date    = c("2021-09-24",
                                       "2021-10-01",
                                       "2021-10-15",
                                       "2021-10-22"),
                           Topic   = c(
                             paste0("[Introduction to Livestock Breeding and Genomics](", s_cn_url, "01_intro_lbg.pdf)", collapse = ""),
                             paste0("[Basics of Quantitative Genetics](", s_cn_url, "02_basic_qg.pdf)", collapse = ""),
                             paste0("[Genetic Evaluation](", s_cn_url, "03_gen_eval.pdf)", collapse = ""),
                             paste0("[BLUP](", s_cn_url, "04_blup.pdf)", collapse = "")
                           ))
knitr::kable(tbl_chpt)
```


# Appendix

```{r appendix-table, echo=FALSE, message=FALSE, warning=FALSE}
s_app_url <- "https://charlotte-ngs.github.io/lbgfs2021/cn/"
tbl_appendix <- tibble::tibble(Nr  = c(1,2),
                               Date = c("2021-09-24", "2021-09-24"),
                               Topic = c(
                                 paste0("[Introduction to Linear Algebra](", s_app_url, "A01_intro_linalg.pdf)", collapse = ""),
                                 paste0("[Introduction to R](", s_app_url, "A02_intro_r.pdf)", collapse = "")
                               ))
knitr::kable(tbl_appendix)
```


```{r latest-changes, echo=FALSE, results='asis', message=FALSE, warning=FALSE}
cat(rmdhelp::get_latest_change())
```

