---
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::knit_hooks$set(hook_convert_odg = rmdhelp::hook_convert_odg)
```

```{bash, echo=FALSE, eval=FALSE}
# bash - export as jpeg
ls -1 /Users/peter/Google\ Drive/Vorlesungen/LBG/FS2021/OHP-L07/* | while read p
do
  CURPICFN=$(basename "$p")
  echo " * Copy $p ..."
  cp "$p" ~/Desktop
  echo " * Convert ~/Desktop/$CURPICFN ..."
  mogrify -resize 50% -format jpg ~/Desktop/$CURPICFN
  echo " * Remove ~/Desktop/$CURPICFN ..."
  rm ~/Desktop/$CURPICFN
  sleep 2
done

```

```{r, echo=FALSE, eval=FALSE}
this_rmd_file <- ifelse(rstudioapi::isAvailable(),
                        rstudioapi::getActiveDocumentContext()$path,
                        whereami::thisfile())


vec_pics <- list.files(path = "~/Desktop", pattern = ".jpg$")
for (pidx in seq_along(vec_pics)){
   cur_pic <- vec_pics[pidx]
   cur_pic_nr <- as.integer(unlist(strsplit(fs::path_ext_remove(cur_pic), "_"))[2])
  cat("\n## OHP Picture ", pidx, "\n\n", sep = "", file = this_rmd_file, append = TRUE)
  cat("```{r ohp-picture", cur_pic_nr, "}\n", sep = "", file = this_rmd_file, append = TRUE)
  cat("rmdhelp::use_odg_graphic(ps_path = 'odg/ohp-page", cur_pic_nr, ".odg')\n", sep = "", file = this_rmd_file, append = TRUE)
  cat("# fs::file_delete(path = '~/Desktop/", cur_pic, "')\n", sep = "", file = this_rmd_file, append = TRUE)
  cat("```\n\n", file = this_rmd_file, append = TRUE)
}
```
